swagger: '2.0'

info:
  version: "v1"
  title : USER_SIGNUP
  description: "This Consists of the Feilds regarding USER_SIGNUP"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /USER_SIGNUP:
    post:
      description: "Regarding USER_SIGNUP"
      summary: USER_SIGNUP
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_SIGNUP
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               USER_SIGNUP_ID : 1
               USER_ID : 2
               USER_NAME : Akhil
               USER_MAIL_ID : Akhil@gmail
               USER_PHONE_NUMBER : 8635862403
               USER_PASSWORD : mac
               USER_IP : 192.01.0.2000
               USER_DATE_CREATED : 2021/06/05 9:00:35
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /USER_REGISTRATION:
    post:
      description: "Regarding USER_REGISTRATION"
      summary: USER_REGISTRATION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_REGISTRATION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                USER_REG_ID : 1
                USER_ID : 1
                USER_AGE : 22
                USER_EXPERIANCE : 2
                USER_GENDER : MALE
                USER_LICENSE_NUMBER : 2543
                FLAT_NO : 5-2-1/65
                STREET_NAME : sevanagar
                CITY_NAME : HYDERADABAD
                STATE_NAME : TELANGANA
                COUNTRY_NAME : INDIA
                ZIP_CODE : 506315
                USER_APPROVED : 2022/06/09
                USER_IP : 192.0.01.20000
                USER_DATE_REGISTERED : 2021/06/09 9:00:01
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /USER_QUALIFIACTION:
    post:
      description: "Regarding USER_QUALIFIACTION"
      summary: USER_QUALIFIACTION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_QUALIFIACTION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                USER_QUAL_ID : 1
                USER_ID : 1
                USER_QUALIFICATION_NAME : MBBS
                INSTITUTE_NAME : OSIMAINA
                PROCUREMENT_YEAR : 2021/06/10
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /USER_SPECIALIZATION:
    post:
      description: "Regarding USER_SPECIALIZATION"
      summary: USER_SPECIALIZATION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_SPECIALIZATION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               USER_SPECIALIZATION_ID : 1,
               USER_ID : 1,
               SPECIALIZATION_NAME: carido
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /USER_DEPARTMENT:
    post:
      description: "Regarding USER_DEPARTMENT"
      summary: USER_DEPARTMENT
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_DEPARTMENT
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              ID : 1
              USER_ID : 2
              DEPT_ID : 405
              DEPT_NAME : Cardic
              DEPT_HEAD : Cheif
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /USER_HOSPITAL:
    post:
      description: "Regarding USER_HOSPITAL"
      summary: USER_HOSPITAL
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_HOSPITAL
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              USER_HOSPITAL_ID : 1
              USER_ID : 2
              HOSPITAL_NAME : CARE 
              HOSPITAL_ADDRESS : 6-3-50/45
              HOSPITAL_CITY: HYDERADABAD
              HOSPPITAL_STATE: TS
              HOSPITAL_ZIP_CODE : 500003
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /patient_personal:
    post:
      description: "Regarding PATIENT_PERSONAL"
      summary: PATIENT_PERSONAL
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PATIENT_PERSONAL
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              PATIENT_ID :  1
              PATIENT_NAME: Akhil
              PHONE_NUMBER: 9848603404
              MAIL_ID : Akhil@gmail,com
              FLAT_NO : 5-1-7
              STREET_NAME" : Srinagar
              CITY_NAME: HYDERADABAD
              STATE_NAME : TS
              COUNTRY_NAME : India
              ZIP_CODE : 506315
              DATE_OF_BIRTH : 1998-12-2
              CREATED_BY : Akhil
              IP_ADDRESS : 192.01.0.2010
              CREATED_DATE : 2021/5/22 11:00:55
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /PATIENT_HEALTH:
    post:
      description: "Regarding PATIENT_HEALTH"
      summary: PATIENT_HEALTH
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PATIENT_HEALTH
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              PATIENT_HEALTH_ID : 1
              PATIENT_ID : 1
              BLOOD_GROUP : B+
              PATIENT_AGE : 22
              PATIENT_WEIGHT : 89
              PATIENT_HEIGHT: 5.8
              PATIENT_SYSTOLIC_BP : 120
              PATIENT_DYASTOLIC_BP: 80
              PATIENT_TEMPARATURE : 90
              CREATED_BY : Akhil
              IP_ADDRESS : 192.01.0.2001
              CREATED_DATE : 2021/06/01 10:00:59
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /SESSION:
    post:
      description: "Regarding SESSION"
      summary: SESSION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - SESSION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                ID : 1
                SESSION_ID : 2
                USER_ID : 207
                PATIENT : 307
                
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /TESTS:
    post:
      description: "Regarding TESTS"
      summary: TESTS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - TESTS
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              SESSION_ID : 1
              TEST_ID : 1
              TEST_NAME : BLOOD_TEST
              DISEASE_NAME : CANCER
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /TEST_RESULT:
    post:
      description: "Regarding TEST_RESULT"
      summary: TEST_RESULT
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - TEST_RESULT
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              SESSION_ID : US001
              TEST_ID : 1
              TEST_RESULT : TESTRESULT
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /SYMPTOM:
    post:
      description: "Regarding SYMPTOM"
      summary: SYMPTOM
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - SYMPTOM
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                SESSION_ID : US455
                SYMPTOM_ID : 1
                SYMPTOM_NAME : COUGH
                INPUT : 1
                
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /CAUSE:
    post:
      description: "Regarding CAUSE"
      summary: CAUSE
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CAUSE
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              SESSION_ID : 1
              CAUSE_ID : 1
              CAUSE_NAME : Cause Name
              INPUT: 1
              
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /LOGS:
    post:
      description: "Regarding LOGS"
      summary: LOGS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - LOGS
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              LOG_ID : 1
              LOGIN_EMAIL_ID: Akhil@gmail.com
              LOGIN_TIME : 2021/06/07 09:00:00
              LOGOUT_TIME: 2021/06/05 19:00:00
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
  /API_LOGS:
    post:
      description: "Regarding API_LOGS"
      summary: API_LOGS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - Api_Logs
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               API_ID : 1
               API_NAME: "API_LOGS"
               ERROR_CODE : 200
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess