swagger: '2.0'

info:
  version: "v1"
  title : USER_QUALIFIACTION
  description: "This Consists of the Feilds regarding USER_QUALIFIACTION"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /USER_QUALIFIACTION:
    post:
      description: "Regarding USER_QUALIFIACTION"
      summary: USER_QUALIFIACTION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_QUALIFIACTION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                USER_QUAL_ID : 1
                USER_ID : 1
                USER_QUALIFICATION_NAME : MBBS
                INSTITUTE_NAME : OSIMAINA
                PROCUREMENT_YEAR : 2021/06/10
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
