swagger: '2.0'

info:
  version: "v1"
  title : REST API for 'STUDENT DETAILS'
  description: |
    "This is the process of geting data about Students and their details."
    In this API we have total four post methods each statement consist of different properties.

    college:
    in this we have mainly four details 
    1 Id
    2 name
    3 department
    4 CGPA

    
    
    reference url : https://swagger.io/docs/open-source-tools/swagger-editor/
    reference url : https://stackoverflow.com/questions/40818908/using-flask-restful-in-spyder
host: 127.0.0.1:5000
basePath: /

tags:
- name: "student"
  description: "Everything about your student details"
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /college/id:
    post:
      summary: Update a details
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          requried: True
          schema:
            example:
             ID: 1
             name: AKhil  
             department: ECE 
             CGPA: 7.8  
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess        
                   
          
          
            
      
     
