swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_OUT_FOR_DELIVERY
  description: "This Consists of the Feilds regarding PHARMA_OUT_FOR_DELIVERY"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"
securityDefinitions:
  bearerAuth:
      type: apiKey
      in: header     
      name: x-access-token

produces:
  - application/json

paths:
  /PHARMA_OUT_FOR_DELIVERY:
    post:
      description: "Regarding PHARMA_OUT_FOR_DELIVERY"
      summary: PHARMA_OUT_FOR_DELIVERY
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_OUT_FOR_DELIVERY
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              PATIENT_ID : 1
              PAYMENT_ID : 2000
              DELIVERY_PERSON_ID : 0001 
              DELIVERY_TIME : "2021-07-30"
              PATIENT_NAME : "Akhil"
              PATIENT_ADDRESS : "hyderabad"
              TYPE_DELIVERY : "COD"
              PICKUP_STATUS : 1
              DELIVERY_STATUS : 1
            type : "string"
            $ref: '#/definitions/Pharmacydashboard/properties/PHARMA_OUT_FOR_DELIVERY'
      responses:
        200:
          description: sucessfull
          examples : 
            application/json : ok

        400:
          description: Bad request
          examples : 
            application/json : bad request
        401:
          description: "Unauthorized  : password must contain Minimum eight characters, at least one letter, one number and one special character"
          examples : 
            application/json : password must contain Minimum eight characters, at least one letter, one number and one special character
        403:
          description: Forbidden
          examples : 
            application/json : Forbidden
          
        404:
          description: Not found
          examples : 
            application/json : Not found
        500:
          description: Internal server error 
          examples : 
            application/json : Internal server error 
        502:
          description: Bad gateway
          examples : 
            application/json : Bad gateway
        503:
          description: Service unavailable
          examples : 
            application/json : Service unavailable
        504:
          description: Gateway timeout
          examples : 
            application/json : Gateway timeout

definitions:
  Pharmacydashboard:
    type: object
    properties:

      PHARMA_OUT_FOR_DELIVERY:
        type: string
        description: "enter the details for PHARMA_OUT_FOR_DELIVERY ."
        example :
                PATIENT_ID : 1
                PAYMENT_ID : 2000
                DELIVERY_PERSON_ID : 0001 
                DELIVERY_TIME : "2021-07-30"
                PATIENT_NAME : "Akhil"
                PATIENT_ADDRESS : "hyderabad"
                TYPE_DELIVERY : "COD"
                PICKUP_STATUS : 1
                DELIVERY_STATUS : 1