swagger: '2.0'

info:
  version: "v1"
  title : TESTS
  description: "This Consists of the Feilds regarding TESTS"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /TESTS:
    post:
      description: "Regarding TESTS"
      summary: TESTS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - TESTS
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              SESSION_ID : 1
              TEST_ID : 1
              TEST_NAME : BLOOD_TEST
              DISEASE_NAME : CANCER
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
