swagger: '2.0'

info:
  version: "v1"
  title : USER_HOSPITAL
  description: "This Consists of the Feilds regarding USER_HOSPITAL"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /USER_HOSPITAL:
    post:
      description: "Regarding USER_HOSPITAL"
      summary: USER_HOSPITAL
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_HOSPITAL
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              USER_HOSPITAL_ID : 1
              USER_ID : 2
              HOSPITAL_NAME : CARE 
              HOSPITAL_ADDRESS : 6-3-50/45
              HOSPITAL_CITY: HYDERADABAD
              HOSPPITAL_STATE: TS
              HOSPITAL_ZIP_CODE : 500003
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess