swagger: '2.0'

info:
  version: "v1"
  title : LOGS
  description: "This Consists of the Feilds regarding LOGS"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /LOGS:
    post:
      description: "Regarding LOGS"
      summary: LOGS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - LOGS
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              LOG_ID : 1
              LOGIN_EMAIL_ID: Akhil@gmail.com
              LOGIN_TIME : 2021/06/07 09:00:00
              LOGOUT_TIME: 2021/06/05 19:00:00
               
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess

