swagger: '2.0'

info:
  version: "v1"
  title : TEST_RESULT
  description: "This Consists of the Feilds regarding TEST_RESULT"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /TEST_RESULT:
    post:
      description: "Regarding TEST_RESULT"
      summary: TEST_RESULT
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - TEST_RESULT
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              SESSION_ID : US001
              TEST_ID : 1
              TEST_RESULT : TESTRESULT
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
