swagger: '2.0'

info:
  version: "v1"
  title : USER_SPECIALIZATION
  description: "This Consists of the Feilds regarding USER_SPECIALIZATION"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /USER_SPECIALIZATION:
    post:
      description: "Regarding USER_SPECIALIZATION"
      summary: USER_SPECIALIZATION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - USER_SPECIALIZATION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               USER_SPECIALIZATION_ID : 1,
               USER_ID : 1,
               SPECIALIZATION_NAME: carido
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
