swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_PAYMENT
  description: "This Consists of the Feilds regarding PHARMA_PAYMENT"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /PHARMA_PAYMENT:
    post:
      description: "Regarding PHARMA_PAYMENT"
      summary: PHARMA_PAYMENT
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_PAYMENT
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               REQUEST_ID : 1
               TRANSACTION_ID : 1
               PAYMENT_TYPE : Online
               PAYMENT_STATUS : 1

              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
