swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_REGISTRATION
  description: "This Consists of the Feilds regarding PHARMA_REGISTRATION"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /PHARMA_REGISTRATION:
    post:
      description: "Regarding PHARMA_REGISTRATION"
      summary: PHARMA_REGISTRATION
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_REGISTRATION
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
                PHARMA_REG_ID : 1
                PHARMA_ID : 1
                PHARMA_RATING : 2
                PHARMA_LICENSE_NUMBER : 2543
                FLAT_NO : 5-2-1/65
                STREET_NAME : sevanagar
                CITY_NAME : HYDERADABAD
                STATE_NAME : TELANGANA
                COUNTRY_NAME : INDIA
                ZIP_CODE : 506315
                PHARMA_APPROVED : 2022/06/09
                PHARMA_IP : 192.0.01.20000
                PHARMA_DATE_REGISTERED : 2021/06/09 9:00:01
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
