swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_MEDICINE_STOCK
  description: "This Consists of the Feilds regarding PHARMA_MEDICINE_STOCK"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /PHARMA_MEDICINE_STOCK:
    post:
      description: "Regarding PHARMA_MEDICINE_STOCK"
      summary: PHARMA_MEDICINE_STOCK
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_MEDICINE_STOCK
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               MEDICINE_NAME : Drops
               PHARMA_ID : 1
               MEDICINE_STOCK_AVAILABILITY : 1
               MEDICINE_MRP : 100
               MEDICINE_DISCOUNT : 0
               MEDICINE_FINAL_PRICE : 100
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
