swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_REQUESTS
  description: "This Consists of the Feilds regarding PHARMA_REQUESTS"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"
securityDefinitions:
  bearerAuth:
      type: apiKey
      in: header     
      name: x-access-token

produces:
  - application/json

paths:
  /PHARMA_REQUESTS:
    post:
      description: "Regarding PHARMA_REQUESTS"
      summary: PHARMA_REQUESTS
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_REQUESTS
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
              PRESCRIPTION_ID : 2
              REQUEST_STATUS : 1
            type : "string"
            $ref: '#/definitions/Pharmacydashboard/properties/PHARMA_REQUESTS'
      responses:
        200:
          description: sucessfull
          examples : 
            application/json : ok

        400:
          description: Bad request
          examples : 
            application/json : bad request
        401:
          description: "Unauthorized  : password must contain Minimum eight characters, at least one letter, one number and one special character"
          examples : 
            application/json : password must contain Minimum eight characters, at least one letter, one number and one special character
        403:
          description: Forbidden
          examples : 
            application/json : Forbidden
          
        404:
          description: Not found
          examples : 
            application/json : Not found
        500:
          description: Internal server error 
          examples : 
            application/json : Internal server error 
        502:
          description: Bad gateway
          examples : 
            application/json : Bad gateway
        503:
          description: Service unavailable
          examples : 
            application/json : Service unavailable
        504:
          description: Gateway timeout
          examples : 
            application/json : Gateway timeout

definitions:
  Pharmacydashboard:
    type: object
    properties:

      PHARMA_REQUESTS:
        type: string
        description: "enter the details for PHARMA_REQUESTS ."
        example :
                PRESCRIPTION_ID : 2000
                REQUEST_STATUS : 1