swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_DELIVERY_PERSON
  description: "This Consists of the Feilds regarding PHARMA_DELIVERY_PERSON"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /PHARMA_DELIVERY_PERSON:
    post:
      description: "Regarding PHARMA_DELIVERY_PERSON"
      summary: PHARMA_DELIVERY_PERSON
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_DELIVERY_PERSON
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               DELIVERY_NAME : Drops
               DELIVERY_PHONE_NUMBER : 9874561230
               DELIVERY_DRIVING_LICENCE_NUMBER : LR001258
               DELIVERY_PRESENT_LOCATION : HYDERADBAD

              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
