swagger: '2.0'

info:
  version: "v1"
  title : PHARMA_SIGNUP
  description: "This Consists of the Feilds regarding PHARMA_SIGNUP"
    
host: 127.0.0.1:5000
basePath: /
  
schemes:
#- "https"
- "http"

produces:
  - application/json

paths:
  /PHARMA_SIGNUP:
    post:
      description: "Regarding PHARMA_SIGNUP"
      summary: PHARMA_SIGNUP
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - PHARMA_SIGNUP
      parameters:
        - name: Body
          in: body
          required: True
          schema:
            example :
               PHARMA_SIGNUP_ID : 1
               PHARMA_ID : 2
               PHARMA_NAME : Akhil
               PHARMA_MAIL_ID : Akhil@gmail
               PHARMA_PHONE_NUMBER : 8635862403
               PHARMA_PASSWORD : mac
               PHARMA_IP : 192.01.0.2000
               PHARMA_DATE_CREATED : 2021/06/05 9:00:35
              
      responses:
        '200':
          description: OK
          examples:
            application/json : Success
        '400':
          description: BAD REQUEST
          examples:
            application/json: unsuccess
